[OUTPUT]
    Name            es
    Match           kube.*
    Host            elasticsearch
    Port            9200
    Index           kubernetes-logs
    Logstash_Format On
    Replace_Dots    On
    Suppress_Type_Name On
    Retry_Limit False
